
export const IMAGES = {
  ARROW: require('../assets/icon/arrow.png'),
  GOOGLE: require('../assets/icon/googleicon.png'),
  EYE: require('../assets/icon/eye.png'),
  ADD: require('../assets/icon/Add.png'),
  ARROW_DOWN: require('../assets/icon/arrow-down.png'),
  CROSS: require('../assets/icon/cross.png'),
  EXPENSE: require('../assets/icon/expense.png'),
  INCOME: require('../assets/icon/income.png'),
  NOTIFICATION: require('../assets/icon/notification.png'),
  RECURRING_BILL: require('../assets/icon/recurring-bill.png'),
  RESTAURANT: require('../assets/icon/restaurant.png'),
  SHOPPING: require('../assets/icon/shopping.png'),
  SUCCESS: require('../assets/icon/success.png'),
  VECTOR: require('../assets/icon/vector.png'),
  GRAPH: require('../assets/images/graph.png'),
  PROFILE: require('../assets/images/profile.png'),
  MENU: require('../assets/icon/menu.png'),
  RIGHT_ARROW: require('../assets/icon/arrow-right.png'),
  WARNING: require('../assets/icon/warning.png'),
  SETTING: require('../assets/icon/settings.png'),
  EDIT: require('../assets/icon/edit.png'),
  FRAME: require('../assets/icon/frame.png'),
  GREENCIRCLE: require('../assets/images/greencircle.png'),
  YELLOWCIRCLE: require('../assets/images/yellowcircle.png'),
  CAR: require('../assets/icon/car.png'),
  SALARY: require('../assets/icon/salary.png'),
  MAINPROFILE: require('../assets/images/mainprofile.png'),
  LOGOUT: require('../assets/icon/logout.png'),
  SORTING: require('../assets/icon/sorting.png'),
  TRASH: require('../assets/icon/trash.png'),
  WHITEARROW: require('../assets/icon/whitearrow.png'),
  DETAILPIC: require('../assets/images/detailpic.png'),
  WHITEINCOME: require('../assets/icon/whiteincome.png'),
  WHITEEXPENSE: require('../assets/icon/whiteexpense.png'),
  ATTACHMENT: require('../assets/icon/attachment.png'),
  FILE: require('../assets/icon/file.png'),
  CAMER: require('../assets/icon/camera.png'),
  GALLERY: require('../assets/icon/gallery.png'),
  

};